Add new addresses flash borrowers
TokenLogic-com-au/aave-proposals-v3 pull request #41
Opened 2024-09-16 14:52 UTC by LucasWongC

2024-09-17 02:32 UTC, defijesus requested changes

2024-09-17 02:32 UTC, defijesus commented on src/20240906_Multi_AddFlashBorrowers/AddFlashBorrowers.md
> +This AIP updated and extends existing whitelisted flashBorrowers addresses to recently deployed instances of Aave v3 on Ethereum.
```suggestion
This AIP updates and extends existing whitelisted flashBorrowers addresses to recently deployed instances of Aave v3 on Ethereum.
```

As of right now the described targeted intances are confusing, it specifies the recently deployed instances while the payload also targets ethereum v3 main instance. My suggestion is to specify of all targeted instances.

2024-09-17 02:32 UTC, defijesus commented on src/20240906_Multi_AddFlashBorrowers/AaveV3Ethereum_AddFlashBorrowers_20240906.sol
> +
according to the specification, shouldnt this instance also include the rest of the flash borrowers included in other ethereum instances? (Lido for example)

2024-09-19 12:38 UTC, Matt-Graham-TL commented on src/20240906_Multi_AddFlashBorrowers/config.ts
> +  poolOptions: {
Contango and IndexCoop are for Ethereum only. See extract below:

`Existing addresses associated with Index Coop and Contango on the Lido and EtherFi instances only.`
https://governance.aave.com/t/arfc-add-cian-protocol-to-flashborrowers/18731

2024-09-19 16:06 UTC, merged