reserve update
TokenLogic-com-au/aave-proposals-v3 pull request #7
Opened 2024-03-22 21:20 UTC by dd0sxx

ready for review. when ready we can open a pr against the bgd repo

2024-04-02 15:43 UTC, efecarranza requested changes

2024-04-02 15:43 UTC, efecarranza commented on src/20240322_AaveV2Polygon_ReserveFactorUpdates/AaveV2Polygon_ReserveFactorUpdates_20240322.sol
> + * @title Reserve Factor Updates (March 15, 2024)
Update title

2024-04-02 15:43 UTC, efecarranza commented on src/20240322_AaveV2Polygon_ReserveFactorUpdates/AaveV2Polygon_ReserveFactorUpdates_20240322.t.sol
> +    vm.createSelectFork(vm.rpcUrl('polygon'), 54963727);
Update block as previous RF had not executed

2024-04-02 15:43 UTC, efecarranza commented on src/20240322_AaveV2Polygon_ReserveFactorUpdates/ReserveFactorUpdates.md
> +This AIP is a continuation of proposal 41 on Governance v3 and increases the Reserve Factor (RF) for assets on Polygon v2 by 5.00%, up to a maximum of 99.99%.
Continuation of 54

2024-04-02 15:43 UTC, efecarranza commented on diffs/AaveV2Polygon_ReserveFactorUpdates_20240322_before_AaveV2Polygon_ReserveFactorUpdates_20240322_after.md
> +| reserveFactor | 83 % | 93 % |
Rerun tests so these update

2024-04-12 09:01 UTC, dd0sxx commented
closing because this was already merged into the bgd repo

2024-04-12 09:01 UTC, closed without merging