onboard gho on lido instance & migrate streams & cancel allowance
TokenLogic-com-au/aave-proposals-v3 pull request #75
Opened 2024-11-05 17:44 UTC by LucasWongC

2024-11-12 11:45 UTC, efecarranza requested changes

2024-11-12 11:45 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +    GHO_SEED_AMOUNT = IERC20(AaveV3EthereumAssets.GHO_UNDERLYING).balanceOf(
There are some streams to the end of the year in GHO. The proposal mentions that amount is TBD instead of all the balance on the collector. Please check with Matt the actual value.

2024-11-20 11:44 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +    GHO_SEED_AMOUNT = IERC20(AaveV3EthereumAssets.GHO_UNDERLYING).balanceOf(
@Matt-Graham-TL can you confirm on this please? Thank you!

2024-11-29 22:22 UTC, efecarranza requested changes

2024-11-29 22:22 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +  uint256 public constant A_USDT_SWAP_AMOUNT = 1_500_000e6;
These are not swap amounts, these are withdraw amounts, I'd rename the variables

2024-11-29 22:22 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +    uint256 meritAllownace = IERC20(AaveV3EthereumAssets.GHO_UNDERLYING).allowance(
Why is this being done in the deposit function instead of execute?

2024-11-29 22:22 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.t.sol
> +      2000000000000, // Hardcoded as dynamic
This isn't dynamic, this is the value of the swaps requested above. It's dynamic when we withdraw an uncertain amount.

2024-11-29 22:22 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.t.sol
> +      1000000000000, // Hardcoded as dynamic
This isn't dynamic, this is the value of the swaps requested above. It's dynamic when we withdraw an uncertain amount.

2024-11-29 22:22 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.t.sol
> +    assertEq(allowance, 0);
Make sure AGD cannot withdraw please

2024-11-29 22:22 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/OnboardGHOAndMigrateStreamsToLidoInstance.md
> +- Acquire GHO from spot market to seed the GHO Reserve on Prime
It's also setting AGD allowance to zero, and adding allowance to Merit

2024-11-29 22:22 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/OnboardGHOAndMigrateStreamsToLidoInstance.md
> +Cancel Aave Grants DAO GHO [Allowance](https://governance.aave.com/t/update-from-aave-grants-winding-down-agd-1-0-and-what-s-next/18707).
Migrate Merit allowances is missing

2024-11-29 22:22 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/OnboardGHOAndMigrateStreamsToLidoInstance.md
> +This proposal includes the following asset swaps:
to GHO and please specify it's Mainnet

2024-11-29 22:25 UTC, efecarranza requested changes

2024-11-29 22:25 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/OnboardGHOAndMigrateStreamsToLidoInstance.md
> +| Collateral Enabled        |                                       true |
Collateral should be disabled

2024-11-29 22:25 UTC, efecarranza commented on diffs/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104_before_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104_after.md
> +| usageAsCollateralEnabled | true |
Collateral should be disabled

2024-11-30 12:48 UTC, Matt-Graham-TL commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +    GHO_SEED_AMOUNT = IERC20(AaveV3EthereumAssets.GHO_UNDERLYING).balanceOf(
We are not migrating any Streams. Only 1 Allowance is to be cancelled on the Collector and then one Allowance of 2M GHO to be created for aLidoEthGHO
.

2024-11-30 12:49 UTC, Matt-Graham-TL commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/OnboardGHOAndMigrateStreamsToLidoInstance.md
> +- Acquire GHO from spot market to seed the GHO Reserve on Prime
Adding 2M Merit Allowance.

2024-11-30 14:41 UTC, LucasWongC commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +    uint256 meritAllownace = IERC20(AaveV3EthereumAssets.GHO_UNDERLYING).allowance(
because treasury can hold aEthGho after deposit

2024-11-30 15:52 UTC, LucasWongC commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/OnboardGHOAndMigrateStreamsToLidoInstance.md
> +- Acquire GHO from spot market to seed the GHO Reserve on Prime
@Matt-Graham-TL 
current implementation is migrate whole allowance at the time of execution, let me know if I need to hardcode to 2M

2024-11-30 20:56 UTC, Matt-Graham-TL commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/OnboardGHOAndMigrateStreamsToLidoInstance.md
> +- Acquire GHO from spot market to seed the GHO Reserve on Prime
If the Allowance was originally 3M, say ACI draws 1M, leaving a balance of 2M on the Allowance... is it a 3M or 2M new Allowance that is created ? We only want the remaining balance.

2024-11-30 23:40 UTC, LucasWongC commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/OnboardGHOAndMigrateStreamsToLidoInstance.md
> +- Acquire GHO from spot market to seed the GHO Reserve on Prime
in that case, 2M allowance is created

2024-12-01 04:12 UTC, efecarranza commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +    uint256 meritAllownace = IERC20(AaveV3EthereumAssets.GHO_UNDERLYING).allowance(
i don't understand, you don't need actual funds for an allowance, you can allow even without funds.

2024-12-03 22:37 UTC, Luigy-Lemon approved these changes
LGTM - I would have made the slippage lower than the 100bps but it's not a big deal.

edit: 
There is no allowance from the Collector to the Merit wallet currently so the allowance migration to ethLidoGHO is essentially migrating a 0 allowance. This needs to be looked at to determine what is the correct step to take,

2024-12-03 23:05 UTC, Luigy-Lemon requested changes
After further look, I believe it needs to be modified because of the existing merit allowance being 0

2024-12-03 23:05 UTC, Luigy-Lemon commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +      100
I would make this 50 since it's between stables.

2024-12-03 23:05 UTC, Luigy-Lemon commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +    if (meritAllownace > 0) {
It is in fact 0 right now. Not sure if this is the correct approach we want to take.

2024-12-03 23:05 UTC, Luigy-Lemon commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +      100
same here

2024-12-03 23:05 UTC, Luigy-Lemon commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.t.sol
> +  }
assertGe(meritAEthGhoAllowanceAfter, 2_000_000 ether);

2024-12-04 12:23 UTC, LucasWongC commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.sol
> +    if (meritAllownace > 0) {
Sep funding proposal has been executed, and current allowance is 3M

2024-12-04 12:24 UTC, LucasWongC commented on src/20241104_AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance/AaveV3EthereumLido_OnboardGHOAndMigrateStreamsToLidoInstance_20241104.t.sol
> +  }
meritAEthGhoAllowanceAfter can be more or less than 2M

2024-12-09 00:29 UTC, closed without merging