September Funding update Part A
TokenLogic-com-au/aave-proposals-v3 pull request #77
Opened 2024-11-14 12:53 UTC by LucasWongC

2024-11-20 20:13 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Polygon_SeptemberFundingUpdatePartA_20241113.sol
> +    AaveV3Polygon.COLLECTOR.transfer(
Same thing applies about 1 unit vs. 1 wei and unnecessary memory expansion

2024-11-20 20:27 UTC, LucasWongC commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Arbitrum_SeptemberFundingUpdatePartA_20241113.t.sol
> +    vm.etch(proposal.USDC_GATEWAY(), address(mock).code);
when fork arbitrum, 0x00...42 contract doesn't work such as onchain

2024-11-21 18:28 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Arbitrum_SeptemberFundingUpdatePartA_20241113.t.sol
> +    vm.expectEmit(address(proposal.BRIDGE()));
`vm.expectEmit(true, true, true, true, address(proposal.BRIDGE()));`

2024-11-21 18:39 UTC, efecarranza requested changes

2024-11-21 18:39 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.sol
> +  address public constant MILKMAN = 0x11C76AD590ABDFFCD980afEC9ad951B160F02797;
Make a note that this will be UPDATED with TODO

2024-11-21 18:39 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.sol
> +  uint256 public constant USDC_A_AMOUNT = 1_250_000_000_000;
Please make 1_250_000e6 or 500_000e18, 500_000 ether, this is hard for reviewers to undesrrtand.

2024-11-21 18:39 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.sol
> +      500
Need to adjust all slippages

2024-11-21 18:39 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.t.sol
> +        0xcE09b7F0eA488160BC0426f31002d7C741b1c921
What is this address?

2024-11-21 18:39 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.t.sol
> +        0xFF3b87a9487380Fb6571A4510ce93d8BF4bcdd4c
What is this address?

2024-11-21 18:39 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.t.sol
> +        0x4648846796341914Ad7a00FA6dBc08555F7d0FB1
What is this address?

2024-11-21 18:39 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Polygon_SeptemberFundingUpdatePartA_20241113.sol
> +    _migrateToken(AaveV3PolygonAssets.USDT_UNDERLYING, AaveV2PolygonAssets.USDT_A_TOKEN, 6);
Decimals are in the address book

2024-11-21 18:39 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Polygon_SeptemberFundingUpdatePartA_20241113.sol
> +    AaveV3Polygon.POOL.deposit(underlying, amount, address(AaveV3Polygon.COLLECTOR), 0);
Use collector utils

2024-11-21 18:39 UTC, efecarranza commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.sol
> +    SWAPPER.swap(
use collector utils

2024-11-21 18:45 UTC, LucasWongC commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.t.sol
> +        0xcE09b7F0eA488160BC0426f31002d7C741b1c921
This is address milkman

2024-11-22 15:05 UTC, Luigy-Lemon reviewed
A few things to fix

2024-11-22 15:05 UTC, Luigy-Lemon commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.t.sol
> +contract AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113_Test is ProtocolV3TestBase {
Was this test ran successfully? There is no diff file in the commit history

2024-11-22 15:12 UTC, LucasWongC commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.sol
> +    uint256 aLusdAvailableBalance = IERC20(AaveV2EthereumAssets.LUSD_UNDERLYING).balanceOf(
yeah. anothers have enough balance. but lusd haven't enough underlying balance in a token contract

2024-11-22 15:15 UTC, LucasWongC commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.t.sol
> +contract AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113_Test is ProtocolV3TestBase {
let me add default test

2024-11-22 15:22 UTC, Luigy-Lemon commented on src/20241113_Multi_SeptemberFundingUpdatePartA/AaveV3Ethereum_SeptemberFundingUpdatePartA_20241113.sol
> +    uint256 aLusdAvailableBalance = IERC20(AaveV2EthereumAssets.LUSD_UNDERLYING).balanceOf(
Ok but you don't know the future... especially for v2 markets it's very unpredictable. This check should be done for all withdrawals.

2024-11-25 16:20 UTC, closed without merging